### ISSUE TITLE
CMSIS-RTOS2 Validation Suite Assertions (PRIMASK == 1)

### ISSUE THREAD

**Issue by MichaelMleczko** [ARM-software/CMSIS-RTOS2_Validation#35]
The CMSIS_RTOS2 validation suite calls CMSIS_RTOS2 API function with PRIMASK set to 1 and expects the functions to return osErrorISR although such behavior is not described in the CMSIS-RTOS2 v2.1.3 documentation.

We have contacted the Arm support and were redirected to GitHUb, but also assured that the validation suite is too restrictive and that this will probably be changed so that CMSIS-RTOS2 API can be called with PRIMASK set to 1 if possible.

Does that mean that we don't need to check anymore if PRIMASK is set and thus don't have to return osErrorISR as long as it is not mentioned in the API documentation?

**Comment by VladimirUmek** [comment]
Hi,

yes, API does not restrict calls from thread with disabled interrupts it only restricts calls from interrupt. Therefore you can ignore asserts that fail when RTOS2 API functions are called from thread with disabled/masked interrupts.

Existing test cases will be most likely modified and the code that tests this situation will be removed.

**Comment by VladimirUmek** [comment]
Mentioned tests were removed from the validation suite.
