### ISSUE TITLE
Online documentation is not accessible

### ISSUE THREAD

**Issue by vovamarch** [ARM-software/CMSIS-RTOS2_Validation#51]
Documentation is generated, but not accessible at commonly expected links:

https://arm-software.github.io/CMSIS-RTOS2_Validation/ 
https://arm-software.github.io/CMSIS-RTOS2_Validation/main/index.html
https://arm-software.github.io/CMSIS-RTOS2_Validation/latest/index.html

Probably some redirects are missing in gh_pages/ structure.

**Comment by VladimirUmek** [comment]
Hi, 
the first two links should now work. Since this repository does not have any release yet, latest/index.html is not functional and won't work.

**Comment by vovamarch** [comment]
Works now, thanks! Understand the limitation for /latest/.
